// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class TradutorServletTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        setupGeckoDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    void setupGeckoDriver() {
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();
        options();
    }

    private void options() {
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void deveriaTraduzirAPalavraArvoreParaTree() {
        driver.get("http://localhost:8080/servlet-mvc-duoulingou/");
        driver.findElement(By.id("palavra")).click();
        driver.findElement(By.id("palavra")).sendKeys("árvore");
        driver.findElement(By.id("btnSubmit")).click();
        assertEquals(
            "A tradução da palavra árvore em inglês é Tree",
            driver.findElement(By.cssSelector("h1")).getText()
        );
    }
    
    // TODO: remover
    @Test
    public void falhaPropositalmente() {
        fail();
    }
}
